openapi: "3.0.0"
info:
  version: 0.0.1
  title: Rowlog navigator API
servers:
  - url: https://asr1.webbies.dk/api/
paths:
  /trips:
    get:
      summary: List all rowing trips
      operationId: listTrips
      tags:
        - trips
      parameters:
        - name: season
          in: query
          description: The season (year) to get trips for.
          required: true
          schema:
            type: integer
            enum:
              - 2021
              - 2022
              - 2023
              - 2024
            format: int32
      responses:
        '200':
          description: A list of trips.
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Trip"
  /members/{id}:
    get:
      summary: Get a member by ID
      operationId: getMemberById
      tags:
        - members
      parameters:
        - name: id
          in: path
          description: The ID of the member to retrieve.
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The member object.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Member"
        '404':
          description: Member not found.

components:
  schemas:
    Trip:
      type: object
      required:
        - i
        - d
        - t
        - b
        - l
        - p
      properties:
        i:
          type: string
          description: A textual description of the trip.
        d:
          type: string
          description: The distance rowed.
        t:
          type: string
          format: date-time
          description: The date and time of the trip.
        b:
          type: string
          description: The name of the boat.
        l:
          type: boolean
          description: Whether the trip is a long trip. (A trip outside of our daily waters.)
        p:
          type: array
          description: The IDs of the members who participated in the trip.
          items:
            type: integer
    Member:
      type: object
      required:
        - id
        - username
        - firstName
        - lastName
        - name
        - email
      properties:
        id:
          type: integer
          format: int32
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        name:
          type: string
        email:
          type: string
