# Taken from https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml

openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://52.252.49.230:9001/api
paths:
  /pets:
    get:
      summary: List all rowing trips
      operationId: listTrips
      tags:
        - trips
      parameters:
        - name: season
          in: query
          description: The season (year) to get trips for.
          required: true
          schema:
            type: integer
            enum:
              - 2021
              - 2022
              - 2023
              - 2024
            format: int32
      responses:
        '200':
          description: A list of trips.
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Trip"
components:
  schemas:
    Trip:
      type: object
      required:
        - id
        - name
        - description
        - distance
        - startDateTime
        - boatName
        - longtrip
        - participants
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        distance:
          type: number
        startDateTime:
          type: string
          format: date-time
        boatName:
          type: string
        longtrip:
          type: boolean
        participants:
          type: array
          items:
            $ref: "#/components/schemas/Member"
    Member:
      type: object
      required:
        - id
        - username
        - firstName
        - lastName
        - name
        - email
      properties:
        id:
          type: integer
          format: int32
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        name:
          type: string
        email:
          type: string
